(function (root) {
  'use strict';

  const SPECIAL = {
    ability_cooldown: ['获取指定技能的剩余冷却时间。', ['技能冷却', '冷却时间', '能力']],
    absolute_time: ['将时间值格式化为绝对时间文本。', ['绝对时间', '时间格式']],
    area_damage_average: ['获取一段时间内的平均区域伤害。', ['平均伤害', '区域伤害', '秒伤']],
    area_damage_per_second: ['获取当前区域的每秒伤害。', ['每秒伤害', '区域秒伤', 'DPS']],
    capped_health: ['获取当前生命值及其上限。', ['生命值', '血量', '生命上限', '血条']],
    capped_mana: ['获取当前魔力及其上限。', ['魔力', '法力', '魔力上限', '蓝条']],
    clock: ['获取当前本地时间。', ['时钟', '本地时间', '几点']],
    concat: ['将多个值拼接成一段文本。', ['拼接文本', '连接字符串', '合并文字']],
    current_raid: ['获取当前 Raid 的名称。', ['当前突袭', 'Raid', '副本']],
    current_territory: ['获取玩家当前所在领地。', ['当前领地', '地区', 'territory']],
    current_world: ['获取玩家当前所在世界或服务器。', ['当前世界', '服务器', '世界编号', 'world']],
    dir: ['获取玩家当前的朝向角度。', ['方向', '朝向', '角度', '指南针']],
    distance: ['计算两个位置之间的距离。', ['距离', '两点距离', '位置']],
    divide: ['计算两个数相除的商。', ['除法', '相除', '计算']],
    dry_aspects: ['获取 Aspect 的未出货计数。', ['未出货计数', 'Aspect']],
    dry_boxes: ['获取箱子稀有奖励的未出货计数。', ['未出货箱数', 'dry box']],
    dry_pulls: ['获取稀有奖励的未出货抽取计数。', ['未出货抽数', 'dry pull']],
    dry_raid_reward_pulls: [
      '获取 Raid 奖励的未出货抽取计数。',
      ['Raid 未出货计数', '奖励抽取', 'Raid 抽数'],
    ],
    dry_raids_aspects: ['获取 Raid Aspect 的未出货计数。', ['Raid Aspect', '未出货计数']],
    dry_raids_tomes: ['获取 Raid Tome 的未出货计数。', ['Raid Tome', '未出货计数']],
    dry_streak: ['获取当前未出货计数。', ['未出货计数', 'dry streak']],
    emerald_block: ['获取钱袋中绿宝石块的数量。', ['绿宝石块', '货币', '钱']],
    equals: ['判断两个数字是否相等。', ['等于', '相等判断', '条件']],
    fps: ['获取当前游戏帧率（FPS）。', ['帧率', 'FPS', '性能', '画面流畅度']],
    greater_than: ['判断第一个数字是否大于第二个数字。', ['大于', '数值比较', '条件']],
    greater_than_or_equals: [
      '判断第一个数字是否大于或等于第二个数字。',
      ['大于等于', '不少于', '数值比较'],
    ],
    health: ['获取玩家当前生命值。', ['生命值', '血量', '当前血量', 'HP']],
    health_max: ['获取玩家的最大生命值。', ['最大生命', '血量上限', 'HP 上限']],
    health_pct: ['获取玩家当前生命值百分比。', ['生命百分比', '血量比例', 'HP 百分比']],
    if_string: [
      '根据布尔条件在两段文本中选择其一。',
      ['条件文本', '如果', '字符串判断', '显示文字'],
    ],
    less_than: ['判断第一个数字是否小于第二个数字。', ['小于', '数值比较', '条件']],
    less_than_or_equals: [
      '判断第一个数字是否小于或等于第二个数字。',
      ['小于等于', '不超过', '数值比较'],
    ],
    location: ['用 X、Y、Z 坐标创建一个位置。', ['坐标位置', '创建位置', 'XYZ']],
    mana: ['获取玩家当前魔力值。', ['魔力', '法力', '当前蓝量', 'Mana']],
    mana_max: ['获取玩家的最大魔力值。', ['最大魔力', '法力上限', 'Mana 上限']],
    mana_pct: ['获取玩家当前魔力值百分比。', ['魔力百分比', '蓝量比例']],
    money: ['获取玩家当前持有的绿宝石总数。', ['金钱', '货币', '绿宝石', '钱袋']],
    my_location: ['获取玩家当前的坐标位置。', ['我的位置', '玩家坐标', '当前位置', 'XYZ']],
    not: ['对布尔条件取反。', ['逻辑非', '不是', '反向条件']],
    not_equals: ['判断两个值是否不相等。', ['不等于', '不同', '条件']],
    ping: ['获取当前的网络延迟。', ['延迟', '网络延迟', 'Ping', '连接']],
    player_name: ['获取当前玩家的名称。', ['玩家名', '角色名', '名字']],
    string: ['将一个值转换为文本。', ['转成文本', '字符串', '格式转换']],
    x: ['获取一个位置的 X 坐标。', ['X 坐标', '横坐标', '位置']],
    y: ['获取一个位置的 Y 坐标。', ['Y 坐标', '高度', '位置']],
    z: ['获取一个位置的 Z 坐标。', ['Z 坐标', '纵坐标', '位置']],
  };

  const WORDS = {
    ability: '技能',
    cooldown: '冷却',
    absolute: '绝对',
    time: '时间',
    accessory: '饰品',
    durability: '耐久',
    activity: '活动',
    color: '颜色',
    icon: '图标',
    name: '名称',
    task: '任务',
    type: '类型',
    add: '相加',
    all: '全部',
    shiny: '闪亮统计',
    stats: '统计',
    and: '并且',
    annihilation: '歼灭战',
    sun: '太阳进度',
    progress: '进度',
    area: '区域',
    damage: '伤害',
    average: '平均值',
    per: '每',
    second: '秒',
    armor: '护甲',
    arrow: '箭矢',
    shield: '护盾',
    count: '数量',
    aspect: 'Aspect',
    tier: '等级',
    at: '处于',
    cap: '上限',
    aura: '光环',
    timer: '计时器',
    blink: '闪烁',
    shader: '着色效果',
    blocks: '方块数',
    above: '上方',
    ground: '地面',
    bomb: '炸弹',
    end: '结束',
    formatted: '格式化',
    string: '文本',
    length: '时长',
    owner: '拥有者',
    remaining: '剩余',
    start: '开始',
    world: '世界',
    brightness: '亮度',
    shift: '调整',
    broken: '破损',
    capped: '当前值和上限',
    awakened: '觉醒',
    blood: '血池',
    pool: '池',
    corrupted: '腐化',
    focus: '专注',
    guild: '公会',
    level: '等级',
    objectives: '目标',
    health: '生命值',
    held: '手持',
    item: '物品',
    holy: '神圣能量',
    ingredient: '材料',
    pouch: '袋',
    slots: '栏位',
    inventory: '背包',
    mana: '魔力',
    bank: '储备',
    mem: '内存',
    memory: '内存',
    mount: '坐骑',
    stat: '属性',
    ophanim: 'Ophanim',
    xp: '经验',
    ceil: '向上取整',
    chest: '宝箱',
    opened: '开启',
    this: '本次',
    session: '会话',
    chosen: '已选',
    buff: '增益',
    buffs: '增益',
    gambit: '策略',
    gambits: '策略',
    clamp: '限制范围',
    class: '职业',
    clock: '时钟',
    commander: '指挥官',
    activated: '已激活',
    duration: '持续时间',
    concat: '拼接',
    styled: '样式化',
    text: '文本',
    contributed: '贡献',
    rank: '排名',
    crow: '乌鸦',
    current: '当前',
    distortion: '扭曲',
    energy: '能量',
    raid: '突袭',
    boss: '首领',
    challenge: '挑战',
    room: '房间',
    territory: '领地',
    tower: '塔',
    attack: '攻击',
    speed: '速度',
    defense: '防御',
    event: '事件',
    debuffs: '减益',
    radius: '范围',
    value: '值',
    dec: '十进制',
    hex: '十六进制',
    dir: '方向',
    distance: '距离',
    divide: '除法',
    dry: '未出货计数',
    aspects: 'Aspect',
    boxes: '箱子',
    pulls: '抽取',
    streak: '连续次数',
    emerald: '绿宝石',
    block: '块',
    emeralds: '绿宝石',
    equals: '等于',
    equipped: '已装备',
    estimated: '预计',
    finish: '完成',
    war: '战争',
    euler: '欧拉常数',
    fade: '淡出',
    floor: '向下取整',
    focused: '锁定目标',
    mob: '生物',
    percent: '百分比',
    format: '格式化',
    date: '日期',
    fps: '帧率',
    friends: '好友',
    from: '从',
    codepoint: '字符码',
    rgb: 'RGB 颜色',
    gathering: '采集',
    totem: '图腾',
    gradient: '渐变',
    greater: '大于',
    than: '',
    or: '或者',
    guardian: '守护',
    angels: '天使',
    objective: '目标',
    score: '分数',
    hades: 'Hades',
    party: '队伍',
    member: '成员',
    location: '位置',
    uuid: 'UUID',
    has: '存在',
    no: '无',
    gui: '界面',
    max: '最大值',
    pct: '百分比',
    highest: '最高',
    hounds: '猎犬',
    hue: '色相',
    hummingbirds: '蜂鸟',
    state: '状态',
    id: 'ID',
    if: '条件选择',
    custom: '自定义',
    number: '数字',
    in: '在',
    mapped: '地图',
    stream: '直播模式',
    open: '空闲',
    used: '已使用',
    initial: '初始',
    integer: '整数',
    free: '空闲',
    is: '是否',
    unlocked: '已解锁',
    allied: '盟友',
    finite: '有限数',
    friend: '好友',
    infinite: '无限数',
    nan: '非数字',
    alive: '存活',
    online: '在线',
    riding: '骑乘',
    horse: '马匹',
    queued: '排队',
    tracking: '追踪',
    judrajim: 'Judrajim',
    active: '生效',
    key: '按键',
    pressed: '按下',
    kills: '击杀',
    minute: '分钟',
    last: '上次',
    dealt: '造成',
    harvest: '采集',
    material: '材料',
    gain: '获得',
    kill: '击杀',
    mythic: '神话物品',
    profession: '生产职业',
    spell: '法术',
    cost: '消耗',
    repeat: '重复',
    leaderboard: '排行榜',
    position: '位置',
    leading: '前导',
    zeros: '零',
    less: '小于',
    liquid: '液体绿宝石',
    log: '对数',
    long: '长整数',
    lootrun: 'Lootrun',
    beacon: '信标',
    vibrant: '鲜艳',
    challenges: '挑战',
    mission: '任务',
    trial: '试炼',
    selected: '已选',
    orange: '橙色',
    expire: '过期',
    rainbow: '彩虹',
    red: '红色',
    rerolls: '重抽',
    sacrifices: '牺牲',
    mantle: '披风',
    map: '映射数值',
    minecraft: 'Minecraft',
    version: '版本',
    mirror: '镜像',
    image: '分身',
    modulo: '取余',
    momentum: '动量',
    money: '金钱',
    potential: '潜力',
    multiply: '乘法',
    my: '我的',
    natural: '自然',
    newest: '最新',
    not: '非',
    now: '当前时间',
    personal: '个人',
    pi: '圆周率',
    ping: '网络延迟',
    pitch: '俯仰角',
    player: '玩家',
    powder: '粉末',
    special: '特殊技能',
    charge: '充能',
    power: '乘方',
    puppet: '傀儡',
    range: '范围',
    high: '高值',
    low: '低值',
    ranged: '范围值',
    regex: '正则表达式',
    find: '查找',
    match: '匹配',
    replace: '替换',
    remnant: '残余',
    round: '四舍五入',
    safe: '安全',
    saturation: '饱和度',
    scoreboard: '计分板',
    seconds: '秒数',
    since: '自从',
    shaman: '萨满',
    mask: '面具',
    poison: '毒素',
    transfused: '转化',
    shine: '闪光',
    snake: '蛇',
    specific: '指定',
    sprint: '冲刺',
    square: '平方',
    root: '根',
    statistics: '统计',
    first: '首次',
    modified: '修改',
    total: '总计',
    status: '状态',
    effect: '效果',
    effects: '效果',
    stopwatch: '秒表',
    hours: '小时',
    milliseconds: '毫秒',
    minutes: '分钟',
    running: '运行中',
    zero: '归零',
    contains: '包含',
    subtract: '减法',
    switch: '分支',
    case: '条件',
    targeted: '选中目标',
    team: '团队',
    dps: '秒伤',
    teleport: '传送',
    scroll: '卷轴',
    charges: '次数',
    recharge: '恢复',
    ticks: '游戏刻',
    token: '代币',
    gatekeeper: '守门人',
    deposited: '已存入',
    effective: '有效',
    hp: '生命',
    transcribe: '转写',
    gavellian: 'Gavellian',
    wynnic: 'Wynnic',
    volley: '齐射',
    wars: '战争次数',
    with: '应用',
    atlas: 'Atlas',
    sprite: '精灵',
    font: '字体',
    bold: '粗体',
    italic: '斜体',
    obfuscated: '乱码',
    resource: '资源',
    shadow: '阴影',
    strikethrough: '删除线',
    underlined: '下划线',
    uptime: '运行时间',
    wrap: '换行',
    wynncraft: 'Wynncraft',
    wynntils: 'Wynntils',
    role: '角色',
    overflow: '溢出',
    req: '所需',
    raw: '原始值',
    percentage: '百分比',
  };

  const TYPE_LABELS = {
    Boolean: '布尔条件',
    CappedValue: '当前值与上限',
    CustomColor: '自定义颜色',
    Double: '小数',
    Float: '小数',
    Integer: '整数',
    Location: '位置',
    Long: '整数',
    NamedValue: '命名值',
    Number: '数字',
    Object: '值',
    RangedValue: '范围值',
    String: '文本',
    StyledText: '样式文本',
    Time: '时间',
  };

  function unique(values) {
    return [
      ...new Set(
        values
          .filter(Boolean)
          .map((value) => String(value).trim())
          .filter(Boolean),
      ),
    ];
  }

  function translateName(name) {
    return unique(name.split('_').map((part) => WORDS[part] || part)).join('');
  }

  const catalog = {};
  (root.WYNNTILS_FUNCTIONS || []).forEach((entry) => {
    const label = translateName(entry.n);
    const result = TYPE_LABELS[entry.r] || entry.r;
    const special = SPECIAL[entry.n];
    catalog[entry.n] = {
      d: entry.d || (special ? special[0] : `获取或计算“${label}”，返回类型为${result}。`),
      kw: unique([
        ...(special ? special[1] : []),
        label,
        ...entry.n.split('_').map((part) => WORDS[part]),
        result,
        entry.n,
        ...entry.a,
      ]),
    };
  });

  root.WYNNTILS_FUNCTIONS_ZH = catalog;
})(typeof globalThis !== 'undefined' ? globalThis : window);
